#! /bin/sh

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DisplayPort-1 -d 11 12 13 14 15 16 17 18 19 20

bspc config border_width 6
bspc config top_padding 30
bspc config window_gap 6
bspc config split_ratio 0.50

bspc config normal_border_color "#000000"
bspc config active_border_color "#808080"
bspc config focused_border_color "#000000"
bspc config presel_feedback_color "#808080"

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer false
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config click_to_focus any
bspc config ignore_ewmh_focus false
#bspc config history_aware_focus true

### Screen 1

# Floating Dialogs
bspc rule -a Dialog state=floating
bspc rule -a lxqt-runner state=floating focus=on follow=on sticky=on center=off border=off
bspc rule -a Zenity state=floating focus=on center=on
bspc rule -a screengrab state=floating focus=on center=on

# 1 - Main Utilities
bspc rule -a pcmanfm-qt desktop=^1 #Temporary
bspc rule -a qterminal desktop=^1 #Temporary
bspc rule -a FeatherPad desktop=^1 #Temporary

# 2 - System Management GUI
bspc rule -a pavucontrol-qt desktop=^2 state=tiled
bspc rule -a qps desktop=^2
bspc rule -a lxqt-config desktop=^2

# 3 - Internet Management GUI
bspc rule -a cmst desktop=^3 state=tiled
bspc rule -a CMST desktop=^3 state=tiled
bspc rule -a Transmission-qt desktop=^3
bspc rule -a qBittorrent desktop=^3

# 4 - Interactive Media Management
bspc rule -a q4wine desktop=^4
bspc rule -a Steam desktop=^4

# 5 - Interactive Media
bspc rule -a Wine desktop=^5 state=floating
bspc rule -a explorer.exe desktop=^5 state=floating
bspc rule -a "Grim Dawn.exe" desktop=^5 state=floating

# 6 - Design Software
bspc rule -a Gimp-2.10 desktop=^6
bspc rule -a godot desktop=^6

### Screen 2

# 11 - Internet Browser
bspc rule -a Firefox desktop=^11 #Temporary
bspc rule -a Nightly desktop=^11 #Temporary
bspc rule -a Navigator desktop=^11 #Temporary

# 12 - Internet Text Communication
bspc rule -a chatterino desktop=^12
bspc rule -a discord desktop=^12
bspc rule -a discord-canary desktop=^12
bspc rule -a ripcord desktop=^12

# 13 - Internet Video Communication
bspc rule -a obs desktop=^13
bspc rule -a zoom desktop=^13

sh ~/Configuration/bspwm/rule-correction.sh
