# prompt.bashrc

PS1="\[${BLACKBG}\] ${CURRENTHOUR}\[${RESET}${BLACKBG}${WHITEFG}\]:\[${RESET}${BLACKBG}\]${CURRENTMINUTE}\[${RESET}${BLACKBG}${WHITEFG}\]:\[${RESET}${BLACKBG}\]${CURRENTSECOND}\[${RESET}${BLACKBG}${WHITEFG}\] \$\[${RESET}${BLACKBG}${BOLD}\]${CURRENTUSER}\[${RESET}${BLACKBG}${WHITEFG}\] @\[${RESET}${BLACKBG}${BOLD}\]${CURRENTHOSTNAME}\[${RESET}${BLACKBG}\] \w \[${RESET}\] "
